name: .NET Build and Publish

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Publish
      run: dotnet publish -c Release -o publish

    - name: Publish artifact details to Devopx
      env:
          ARTIFACTORY_TOKEN: ${{ secrets.ARTIFACTORY_APIKEY }}
      run: |
        # Install Devopx CLI
        npm install --location=global devopx-cli
          
        # Set fixed artifact name and target artifact path
        ARTIFACT_NAME="my-dynamic-app.zip"
        ARTIFACTORY_PATH="dotnet-dynamic-app-local/ci-artifact"
        # Create a timestamp in YYYYMMDDHHMMSS format for versioning
        DATE=$(date +%Y%m%d%H%M%S)
        # Use the same filename as the artifact name
        # Set the full local path for the zip file (current working directory)
        
        # Zip the publish folder into the zip file
        zip -r ${ARTIFACT_NAME} publish

        echo "Artifact Name: $ARTIFACT_NAME"
        echo "Artifact Type: code-zip"
        echo "Artifact Version: $DATE"
        echo "Artifact Path: $ARTIFACTORY_PATH"
        echo "Local Path: $ARTIFACT_NAME"
        echo "File Name: my-dynamic-app-$DATE.zip"
        echo "Artifactory Token: $ARTIFACTORY_TOKEN"

        ls -l ${ARTIFACT_NAME}
        echo "Publishing artifacts  using the Devopx CLI"
        # Publish the artifact details using the Devopx CLI
        devopx publish-artifact \
          --artifact_name="$ARTIFACT_NAME" \
          --artifact_type="code-zip" \
          --artifact_version="$DATE" \
          --artifactory_path="$ARTIFACTORY_PATH" \
          --local_path="$ARTIFACT_NAME" \
          --artifactory_token="$ARTIFACTORY_TOKEN" \
          --file_name="my-dynamic-app-$DATE.zip"